// <auto-generated />
using System;
using MOD.TrainingService.DBContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MOD.TrainingService.Migrations
{
    [DbContext(typeof(TrainingContext))]
    [Migration("20191114060230_TrainingMigration")]
    partial class TrainingMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MOD.TrainingService.Models.Mentor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("TrainingId");

                    b.Property<bool>("active");

                    b.Property<bool>("confirmedSignup");

                    b.Property<long>("contactNumber");

                    b.Property<string>("firstName")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("lastName")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("linkedinUrl")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("registrationCode")
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("resetPassword");

                    b.Property<DateTime>("resetPasswordDate");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("yearsOfExperience");

                    b.HasKey("Id");

                    b.HasIndex("TrainingId");

                    b.ToTable("Mentors");
                });

            modelBuilder.Entity("MOD.TrainingService.Models.Skill", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Fees");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Prerequisites")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("TOC")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("duration");

                    b.HasKey("ID");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("MOD.TrainingService.Models.Training", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("amountReceived");

                    b.Property<DateTime>("endDate");

                    b.Property<string>("endTime");

                    b.Property<string>("mentorName")
                        .HasColumnType("varchar(100)");

                    b.Property<long>("mentorsId");

                    b.Property<int>("progress");

                    b.Property<float>("rating");

                    b.Property<long>("skillId");

                    b.Property<string>("skillName")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("startDate");

                    b.Property<string>("startTime");

                    b.Property<string>("status")
                        .HasColumnType("varchar(1)");

                    b.Property<long>("userId");

                    b.Property<string>("userName")
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("skillId")
                        .IsUnique();

                    b.HasIndex("userId")
                        .IsUnique();

                    b.ToTable("Trainings");
                });

            modelBuilder.Entity("MOD.TrainingService.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("active");

                    b.Property<bool>("confirmedSignup");

                    b.Property<long>("contactNumber");

                    b.Property<string>("email")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("firstName")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("lastName")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("linkedinUrl")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("registrationCode")
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("resetPassword");

                    b.Property<DateTime>("resetPasswordDate");

                    b.Property<string>("role")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("yearsOfExperience");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MOD.TrainingService.Models.Mentor", b =>
                {
                    b.HasOne("MOD.TrainingService.Models.Training", "Training")
                        .WithMany()
                        .HasForeignKey("TrainingId");
                });

            modelBuilder.Entity("MOD.TrainingService.Models.Training", b =>
                {
                    b.HasOne("MOD.TrainingService.Models.Skill", "Skill")
                        .WithOne("Training")
                        .HasForeignKey("MOD.TrainingService.Models.Training", "skillId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MOD.TrainingService.Models.User")
                        .WithOne("Training")
                        .HasForeignKey("MOD.TrainingService.Models.Training", "userId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
